### ISSUE TITLE
Support Wasm SIMD extensions

### ISSUE THREAD

**Issue by bvibber** [bvibber/ogv.js#124]
Not sure what the state of functionality and support is yet, but this might be easier than using the GPU via texture shaders to try to accelerate things internal to the libraries. Emscripten exposes these as intrinsics so it should be relatively straightforward to stick in some extended C code for the acceleratable functions.

**Comment by tomByrer** [comment]
In progress for Chrome, looks like the API isn't settled, so maybe chime in?

https://twitter.com/DasSurma/status/1098915542608609280

**Comment by brion** [comment]
Starting to test this on simd2 branch, just building with the llvm backend and creating an autovectorized build of the AV1 decoder so far that's failing. Will add the other decoders once we get the first failure worked out -- see https://github.com/emscripten-core/emscripten/issues/8175

**Comment by brion** [comment]
It's starting to sortof work. :D This is all very experimental and fragile, so it's minefield territory. :D

But I do see a moderate improvement from hacking some SIMD intrinsics into the dav1d cdef 8x8 block filter. This is careful work and sometimes I'm hitting bugs in the compiler and in Chrome/V8.

**Comment by brion** [comment]
Current compiler or browser issues:

Problem with i32x4.splat breaking autovectorized loops in dav1d:
* https://github.com/emscripten-core/emscripten/issues/8175 / https://bugs.chromium.org/p/v8/issues/detail?id=8927
* worked around by disabling autovectorization

Problem with i16x8.shr_s being broken in V8, and the compiler working around it by doing a scalar op:
* https://github.com/emscripten-core/emscripten/issues/8220 / https://bugs.chromium.org/p/v8/issues/detail?id=8934
* until it's fixed, the bit-shift ops aren't fully vectorized, so we're not getting as big a benefit as we should.

**Comment by brion** [comment]
It's working correctly I think now, with about a 15% or so decode time improvement on 360p sample with the cdef filter manually vectorized, despite the shift problem and the splat workaround.

Will try the next big pred tap functions in a bit, after confirming everything's bit-correct with checksums.

**Comment by brion** [comment]
With put_8tap and prep_8tap and improvements on cdef, I'm up to 28% reduction in decode time as of a couple days ago. Nice! Should improve once can remove shift and splat workarounds. Might be worth further function optimizations, starting with the loopfilter restoration (replacing `wiener_c` & `selfguided_filter`), as the next biggest functions after those already vectorized.

**Comment by brion** [comment]
My biggest complaint is the lack of widening loads and narrowing stores, and lack of native `min`, `max`, and `abs` operations for integers. These can all be emulated with comparisons and `bitselect`, but I'm sure there's some cost in performance. There are some notes to this effect over on the SIMD proposal repo issues, but I'm not sure how serious any proposals to add them are at this point. (Would require researching what ops are available on various arches, I suppose.)

**Comment by brion** [comment]
Up to about 40% reduction in decode time with the wiener filter done and some more optimizations on the other bits. Super nice!

**Comment by brion** [comment]
Splat bug is fixed. Shift bug is still there. Have removed some of the splat bug workarounds except where they fed poorly into the shift bug. ;)

Once shift bug is fixed, can remove the shift_hack() and splat_hack() workarounds and should get another speed boost out of native vector shift operations.

**Comment by brion** [comment]
Works pretty awesome still. Can now build with mainline emscripten too.

Will start on VP9 in a bit maybe.

**Comment by bvibber** [comment]
dav1d has some custom work for wasm simd, i'm just letting the other libraries build with autovectorization on 2.0 work. Considering doneish on 2.0 work branch (now in main)
