### ISSUE TITLE
clean up object-fit emulation

### ISSUE THREAD

**Issue by bvibber** [bvibber/ogv.js#377]
It seems to mostly work in more recent browsers except where it doesn't ;)

and the code is kinda nasty

**Comment by brion** [comment]
Quick compat testing:

OS X:
* Safari 6.1 on 10.7 does not support object-fit on canvas; detects as unavailable
* Safari 6.2 on 10.8 does support it
* Safari 9.1 on 10.9+ does

iOS:
* Safari on iOS 9.3 still messes up the positioning in the demo, though it works fine on my minimal test at https://brionv.com/misc/object-fit/

GRRRR

Edge still hasn't added object-fit either.

**Comment by brion** [comment]
Ok I think I figured out the iOS Safari issue -- it's specific to *WebGL* canvases; 2d canvas doesn't have the positioning problem.

**Comment by bvibber** [comment]
This has been removed due to obselescence
