### ISSUE TITLE
Aim for 0-copy between StreamFile and demuxer

### ISSUE THREAD

**Issue by bvibber** [bvibber/ogv.js#444]
In the new StreamFile code there's an extra copy between the backing buffer and the demuxer, which increases memory usage and CPU time. Would be nice to expose the buffers more directly for more efficient reading, then only do the copy at the end. Look at the internals in the JS webm demuxer to confirm API suitability. :)

**Comment by brion** [comment]
Looking at https://github.com/FlareMediaPlayer/FlareWebmDemuxer/blob/master/src/DataInterface.js in more detail... yes this is making more sense to me now. :) We've ended up with overlap between DataInterface and StreamFile in that they both now manage buffers, so once the demuxer is given a StreamFile directly we can avoid pre-splitting the input buffers into chunks and re-assembling them inside the demuxer, instead reading directly from the StreamFile's internal buffers.

(Internally it's still in chunks, but they may be differently sized depending on network conditions, caching, etc. Plus the StreamFile has a more advanced buffer management in terms of keeping old data so you can seek within buffered areas; avoiding exposing this logic to the demuxers should simplify writing more of them!)

Might be best to expose byte-reading methods on the StreamFile interface; then the DataInterface doesn't have to manage its own buffers (instead using StreamFile's backing buffers), but can concentrate on pulling octets and doing the higher-level work like reading variable-length element ids and vints.

When we get to the packet payload, it can be pulled as a single chunk, with the boundary-spanning copies done within StreamFile.

Todo:
* add readUint8(), readInt8(), etc methods on StreamFile
* finish adapting the player logic to delegate the stream to the demuxer once opened
* adapt the emscripten demuxer to handle input via stream
* adapt the pure-JS demuxer to handle its input via stream

**Comment by brianxautumn** [comment]
Yeah data interface is going to be cleaned up. I think it only really needs one pointer to a buffer and its absolute offset from the entire file.

**Comment by brianxautumn** [comment]
Also we should get rid of array push and pop. It's really inefficient, should be abstracted away with a manual queue module that keeps track of its own fixed size arrays.

**Comment by bvibber** [comment]
gonna refactor all this stuff but not worry about this exact issue
