### ISSUE TITLE
431 Request Header Fields Too Large - ogv wasm

### ISSUE THREAD

**Issue by rtman** [bvibber/ogv.js#578]
Hi,

I'm getting the following error in both firefox and safari:

Safari:

<img width="474" alt="Screen Shot 2020-12-10 at 4 32 16 PM" src="https://user-images.githubusercontent.com/20849135/101846199-53b24780-3b05-11eb-901a-c73d1f930da0.png">

<img width="737" alt="Screen Shot 2020-12-10 at 4 39 27 PM" src="https://user-images.githubusercontent.com/20849135/101846657-49447d80-3b06-11eb-8a68-8143f8504574.png">

Firefox:

<img width="622" alt="Screen Shot 2020-12-10 at 4 38 06 PM" src="https://user-images.githubusercontent.com/20849135/101846600-2dd97280-3b06-11eb-961e-e255a5c1b7f5.png">

Any idea how to fix this issue?

**Comment by rtman** [comment]
This appears to go away if i copy the source files directly to the public directory and use that as the base path. Using 'node_modules/ogv/dist' doesnt seem to work for me. Additionally `import ogv from 'ogv'` doesn't work either, webpack errors, var ogv = require('ogv') seems to work.

**Comment by brion** [comment]
How is this loaded? Is it a webpack package? How are you loading things? Is the source available?

**Comment by rtman** [comment]
This was in a react based project, using npm and importing the package. It's been a while so I don't fully remember but should be reproduceable with a fresh react project.
